---
title: "maincode"
format:
  html:
    embed-resources: true
---
```{r}
library(tidyverse)
library(stringr)
avg.reg.season.attendance.WNBA.2024 <- read.csv("~/avg.reg.season.attendance.WNBA.2024.txt")
NBA.avg.reg.season.attendance.2024 <- read.csv("~/NBA.avg.reg.season.attendance.2024.txt")
highest.paid.players.WNBA <- read.csv("~/highest.paid.players.WNBA.txt")
WNBA_team_2024 <- read.csv("~/WNBA_team_2024.txt")
highest.paid.players.NBA <- read.csv("C:/Users/schro/Downloads/Project Data - Highest-paid NBA players in 2024_25.csv")
teams.by.player.salaries.NBA <- read.csv("C:/Users/schro/Downloads/Project Data - NBA teams ranked by player salaries in 2023_2024.csv")
`team.by.revenue.23-24.NBA` <- read.csv("C:/Users/schro/Downloads/Project Data - NBA teams ranked by revenue in 2023_24.csv")
avg.franchise.value.NBA <- read.csv("C:/Users/schro/Downloads/Project Data - Average franchise value of NBA teams from 2001 to .csv")
est.share.league.revenue.players.WNBA.NBA <- read.csv("C:/Users/schro/Downloads/Project Data - Estimated share of league revenue received by play.csv")
`league,share_of_league_revenue` <- read.csv("~/league,share_of_league_revenue.txt")
```

```{r}
highest.paid.players.NBA <-
  highest.paid.players.NBA |>
  separate(player, into = c("player", "team"), sep = "\\(") |>
  mutate(league = "NBA", salary_in_M = salary, salaries = salary_in_M*1000000) |> select(league, player, salaries, team)

highest.paid.players.WNBA <- highest.paid.players.WNBA |>
  mutate(league = "WNBA", salaries = salary) |> select(league, player, salaries, team)

highest.paid.players <- bind_rows(highest.paid.players.NBA, highest.paid.players.WNBA)

nba_data_2024 <- 
  left_join(teams.by.player.salaries.NBA, `team.by.revenue.23-24.NBA`, by = "team") |>
  mutate(year = 2024) |>
  left_join(avg.franchise.value.NBA, by = "year") |>
  left_join(NBA.avg.reg.season.attendance.2024, by = "team") |>
  mutate(attendance_2024 = X2024, attendance_2023 = X2023, league_revenue_in_.M = franchise_value_in_.M) |>
  select(team, payroll_in_.M, revenue_in_.M, league_revenue_in_.M, attendance_2024, attendance_2023) |> mutate(league = "NBA")

wnba_data_2024 <-
  left_join(WNBA_team_2024, avg.reg.season.attendance.WNBA.2024, by = "team") |> 
  mutate(attendance_2024 = X2024, attendance_2023 = X2023, payroll_in_.M = total_salaries_in_.M, revenue_in_.M = est_revenue_in_.M) |>
  select(team, payroll_in_.M, revenue_in_.M, attendance_2024, attendance_2023) |>
  mutate(league_revenue_in_.M = 200, league = "WNBA")

combined_data <- bind_rows(nba_data_2024, wnba_data_2024)
```

```{r}
#compares 2024 attendance
combined_data |>
  ggplot(mapping = aes(x = fct_reorder(team, attendance_2024), y = attendance_2024, fill = league)) +
  geom_col(position = "dodge") +
  coord_flip() +
  theme_minimal() +
  labs(title = str_wrap("Average attendance of NBA and WNBA games by team during the 2024 season"), x = "Team", y = "Average Attendance", fill = "League")

#compares team salaries to team revenue
nba_data_2024 |>
  mutate(Payroll = payroll_in_.M, Revenue = revenue_in_.M) |>
  select(team, Payroll, Revenue) |>
  pivot_longer(cols = -team, names_to = "variable", values_to = "value" ) |>
  ggplot(mapping = aes(x = team, y = value, fill = variable)) +
  geom_col(width = .8, position = "dodge", col = "white") +
  coord_flip() +
  scale_y_log10() +
  theme_minimal() +
  labs(title = str_wrap("2024 Season Payroll vs. Revenue of NBA Teams"), x = "Team", y = "Millions of Dollars", fill = " ")

wnba_data_2024 |>
  mutate(Payroll = payroll_in_.M, Revenue = revenue_in_.M) |>
  select(team, Payroll, Revenue) |>
  pivot_longer(cols = -team, names_to = "variable", values_to = "value" ) |>
  ggplot(mapping = aes(x = team, y = value, fill = variable)) +
  geom_col(width = .8, position = "dodge", col = "white") +
  coord_flip() +
  scale_y_log10() +
  theme_minimal() +
  labs(title = str_wrap("2024 Season Payroll vs. Revenue of WNBA Teams"), x = "Team", y = "Millions of Dollars", fill = " ", line = "League Revenue")

#given ratio between NBA and WNBA
`league,share_of_league_revenue` |>
  ggplot(mapping = aes(x = league, y = share_of_league_revenue)) +
  geom_col(col = "white") +
  theme_minimal() +
  labs(title = str_wrap("Estimated Share of League Revenue in Annual Wages of Players in the NBA and WNBA in 2024"), x = "League", y = "Percent of Revenue")

combined_data |>
  group_by(league) |>
  summarize(Payroll = sum(payroll_in_.M), Revenue = sum(revenue_in_.M)) |>
  pivot_longer(cols = -league, names_to = "variable", values_to = "value" ) |>
  ggplot(mapping = aes(x = league, y = value, fill = variable)) +
  geom_col(col = "white", position = "dodge") +
  #scale_y_log10() +
  theme_minimal() +
  labs(title = str_wrap("Estimated Share of League Revenue in Annual Wages of Players in the NBA and WNBA in 2024"), x = "League", y = "Log Scale in $M", fill = " ")

combined_data |>
  group_by(league) |>
  summarize(Payroll = sum(payroll_in_.M), Revenue = sum(revenue_in_.M)) |>
  select(league, Payroll, Revenue) |>
  pivot_longer(cols = -league, names_to = "variable", values_to = "value" ) |>
  ggplot(mapping = aes(x = variable, y = value)) +
  geom_col() +
  facet_wrap(vars(league)) +
  theme_minimal() +
  labs(title = str_wrap("Estimated Share of League Revenue in Annual Wages of Players in NBA and WNBA in 2024"), x = "Type", y = "Millions of Dollars")

#highest paid players in each league
highest.paid.players |>
  ggplot(mapping = aes(x = player, y = salaries, fill = league)) +
  geom_col() +
  scale_y_log10() +
  coord_flip() +
  theme_minimal() +
  labs(title = str_wrap("Highest Paid Players in NBA and WNBA in 2024"), x = "Player", y = "Salary", fill = "League")

```

